apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: v1
  name: nginx-named-port
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-named-port
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-named-port
    spec:
      containers:
      - image: nginx:1.22
        resources:
          requests:
            cpu: "100m"      
            memory: "64Mi"   
          limits:
            cpu: "200m"       
            memory: "128MI"
        name: nginx
        ports:
        - name: http-port
          containerPort: 80
        resources: {}
status: {}
