apiVersion: v1
kind: LimitRange
metadata:
  name: practice-d-xolmatov-limits
spec:
  limits:
  - type: Container
    default:
      cpu: "200m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
  
